-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 21:01:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `nome` INT NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `idAlunos` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` INT(11) NOT NULL,
  `rg` INT(11) NOT NULL,
  PRIMARY KEY (`idAlunos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas` (
  `idCursos` INT NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `data` DATE NULL,
  `turmas` VARCHAR(45) NULL,
  `Alunos_idAlunos` INT NOT NULL,
  PRIMARY KEY (`idCursos`),
  INDEX `fk_Turmas_Alunos_idx` (`Alunos_idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_Alunos`
    FOREIGN KEY (`Alunos_idAlunos`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `idClientes` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `frond end` VARCHAR(10) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `Alunos_idAlunos` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Alunos1_idx` (`Alunos_idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Alunos1`
    FOREIGN KEY (`Alunos_idAlunos`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas_has_Cursos` (
  `Turmas_idCursos` INT NOT NULL,
  `Cursos_idClientes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Turmas_idCursos`, `Cursos_idClientes`),
  INDEX `fk_Turmas_has_Cursos_Cursos1_idx` (`Cursos_idClientes` ASC) VISIBLE,
  INDEX `fk_Turmas_has_Cursos_Turmas1_idx` (`Turmas_idCursos` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_has_Cursos_Turmas1`
    FOREIGN KEY (`Turmas_idCursos`)
    REFERENCES `mydb`.`Turmas` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idClientes`)
    REFERENCES `mydb`.`Cursos` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  `nome` VARCHAR(100) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `valor_hora` INT NOT NULL,
  `certificado` INT NOT NULL,
  `Cursos_idClientes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nome`, `Cursos_idClientes`),
  INDEX `fk_professores_Cursos1_idx` (`Cursos_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_professores_Cursos1`
    FOREIGN KEY (`Cursos_idClientes`)
    REFERENCES `mydb`.`Cursos` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores_has_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores_has_Turmas` (
  `professores_nome` VARCHAR(100) NOT NULL,
  `professores_Cursos_idClientes` INT UNSIGNED NOT NULL,
  `Turmas_idCursos` INT NOT NULL,
  PRIMARY KEY (`professores_nome`, `professores_Cursos_idClientes`, `Turmas_idCursos`),
  INDEX `fk_professores_has_Turmas_Turmas1_idx` (`Turmas_idCursos` ASC) VISIBLE,
  INDEX `fk_professores_has_Turmas_professores1_idx` (`professores_nome` ASC, `professores_Cursos_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_Turmas_professores1`
    FOREIGN KEY (`professores_nome` , `professores_Cursos_idClientes`)
    REFERENCES `mydb`.`professores` (`nome` , `Cursos_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_Turmas_Turmas1`
    FOREIGN KEY (`Turmas_idCursos`)
    REFERENCES `mydb`.`Turmas` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
